// Header generated by RemObjects Elements for Cocoa 

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#import <objc/NSObject.h>
#import <Foundation/Foundation.h>

@class SharedClassTest;

@interface SharedClassTest: NSObject

- (void)databaseSetup;
- (void)httpCall:(_Nonnull /* mapped */ NSString *)url completion:(_Nonnull void (^)(/* mapped */ NSString * ))completion;

@end

