// Header generated by RemObjects Elements for Cocoa 

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#import <objc/NSObject.h>
#import <Foundation/Foundation.h>

@class SharedClassTest;
@class BaseObject;
@class CacheObject;

@interface SharedClassTest: NSObject

- (id)init;
- (void)setup;
- (void)storageAdd:(CacheObject *)object;
- (void)storageFlush;
- (void)getJsonObject:(_Nonnull /* mapped */ NSString *)aUrl success:(_Nonnull void (^)(CacheObject * ))success error:(_Nonnull void (^)(NSException * ))error;
- (void)getJsonString:(_Nonnull /* mapped */ NSString *)aUrl success:(_Nonnull void (^)(/* mapped */ NSString * ))success error:(_Nonnull void (^)(NSException * ))error;
- (void)postJsonString:(_Nonnull /* mapped */ NSString *)aUrl parameters:(/* mapped */ NSMutableDictionary *)parameters success:(_Nonnull void (^)(/* mapped */ NSString * ))success error:(_Nonnull void (^)(NSException * ))error;

@end

@interface BaseObject: NSObject

- (id)init;
- (NSString *)ToJson;
- (/* mapped */ NSMutableDictionary *)toJsonObject;
- (void)map:(NSString *)jsonString;

@end

@interface CacheObject: BaseObject

- (id)initWithKey:(NSString *)key value:(NSString *)value timestamp:(NSString *)timestamp;

@property (strong) NSString *key;
@property (strong) NSString *value;
@property (strong) NSString *timestamp;

@end

