// Header generated by RemObjects Elements for Cocoa 

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#import <objc/NSObject.h>
#import <Foundation/Foundation.h>

@class SQLiteConnection;
@class SQLiteQueryResult;
@class SQLiteException;

@interface SQLiteConnection: NSObject

- (id)init:(/* mapped */ NSString *)aFilename :(BOOL)aReadOnly :(BOOL)aCreateIfNeeded;
- (void)BegInTransaction;
- (void)Commit;
- (void)Rollback;
- (int64_t)ExecuteInsert:(/* mapped */ NSString *)aSQL :(NSObject * * /* dynamicarray */)aArgValues;
- (int64_t)Execute:(/* mapped */ NSString *)aSQL :(NSObject * * /* dynamicarray */)aArgValues;
- (SQLiteQueryResult *)ExecuteQuery:(/* mapped */ NSString *)aSQL :(NSObject * * /* dynamicarray */)aArgValues;

@property (readonly,assign) BOOL InTransaction;

@end

@interface SQLiteQueryResult: NSObject

- (id)init:(int64_t)aDB :(int64_t)aRes;
- (BOOL)MoveNext;
- (NSNumber *)GetInt:(int32_t)aIndex;
- (NSNumber *)GetInt64:(int32_t)aIndex;
- (NSNumber *)GetDouble:(int32_t)aIndex;
- (uint8_t * /* dynamicarray */)GetBytes:(int32_t)aIndex;
- (/* mapped */ NSString *)GetString:(int32_t)aIndex;

@property (readonly,assign) int32_t ColumnCount;
@property (readonly,strong) /* mapped */ NSString *ColumnName;
@property (readonly,assign) int32_t ColumnIndex;
@property (readonly,assign) BOOL IsNull;

@end

@interface SQLiteException: NSException

- (id)init:(/* mapped */ NSString *)s;

@end

